sipsorcery-core/SIPSorcery.SIP.App/SIPUserAgents/SIPClientUserAgent.cs, sipsorcery-core/SIPSorcery.SIP.App/SIPUserAgents/SIPServerUserAgent.cs, sipsorcery-core/SIPSorcery.SIP.Core/SIPAuthorisation/SIPAuthorisationDigest.cs
- Add : Hangup method inside SIPClientUserAgent.
- Add : Hangup method inside SIPServerUserAgent.
- Add : IncrementNonceCount method inside SIPAuthorisationDigest.
These two Hangup methods first send a BYE request, if the response is Unauthorize, the auth header is uncluded and the BYE request resend with it.
The IncrementNonceCount method allow the SIPClientUserAgent to increment the NonceCount when the CANCEL request is send with the authorization header.
=> Issue #58 :

sipsorcery-core/SIPSorcery/SIPSorcery.csproj, sipsorcery-core/Tests/SIPSorcery.UnitTests/SIPSorcery.UnitTests.csproj
This allows to reference `SIPSorcery` assembly in projects which are targeted .NET 4.5.2.
Also changed `SIPSorcery.UnitTests` project `TargetFramework` property to `netcoreapp2.0` to support this project in Visual Studio 2017 without additional SDKs.
=> Added net452 target to TargetFrameworks list for wider compatibility

examples/sipsorcery-softphonev2/SIPSorcery.SoftPhone/App.config, examples/sipsorcery-softphonev2/SIPSorcery.SoftPhone/SIPSorcery.SoftPhone.csproj, examples/sipsorcery-softphonev2/SIPSorcery.SoftPhone/Signalling/SIPClient.cs, examples/sipsorcery-softphonev2/SIPSorcery.SoftPhone/packages.config
* Fixed `App.config` assembly name in `section` attribute (for `SIPSorcery.Sys.AppState` type)
* Proper closing of established incoming SIP call (should fix https://github.com/sipsorcery/sipsorcery/issues/77)
* Updated nuget package [SIPSorcery](https://www.nuget.org/packages/SIPSorcery/) to latest version 3.0.1
=> Several fixes for sipsorcery-softphonev2 example application

src/sys/Net/FreePort.cs
This fixes exception with global mutex on OSX.
`Exception has occurred: CLR/System.IO.IOException
An unhandled exception of type 'System.IO.IOException' occurred in System.Private.CoreLib.dll: 'The filename, directory name, or volume label syntax is incorrect. : 'Global/8875BD8E-4D5B-11DE-B2F4-691756D89593''
at System.Threading.Mutex.CreateMutexCore(Boolean initiallyOwned, String name, Boolean& createdNew)
at System.Threading.Mutex..ctor(Boolean initiallyOwned, String name)
at SIPSorcery.Sys.FreePort.FindNextAvailableUDPPort(Int32 startPort) in /Users/dtarasov/Documents/projects/graphone/sipsorcery/src/sys/Net/FreePort.cs:line 84
.............`
=> Fixed exception with mutex in FindNextAvailableUDPPort

src/app/SIPUserAgents/SIPRegistrationUserAgent.cs, src/core/SIP/Channels/SIPUDPChannel.cs
There is a problem in SIPUDPChannel closing. When you create SIPUDPChannel it starts a new thread to listen for incoming packets with `buffer = m_sipConn.Receive()` Then when you want to stop channel you call `SIPUDPChannel.Close()` with `m_sipConn.Close()` inside it from another thread. You think that it should interrupt `m_sipConn.Receive()` but it will not. It will stuck on `m_sipConn.Close()` until `m_sipConn.Receive()` returns.
To see this problem in action you can make a little change in UserAgentRegister example. Just change code in the end of `Main()` on
`
// Start the thread to perform the initial registration and then periodically resend it.
regUserAgent.Start();
taskCompleteMre.WaitOne();
Thread.Sleep(2000); // <- This is the interesting part
regUserAgent.Stop();
if …
=> Sipudpchannel close fix

examples/AllExamples.sln, examples/UserAgentClient/Program.cs, examples/UserAgentClient/Properties/launchSettings.json, examples/UserAgentClient/UserAgentClient.csproj, examples/UserAgentServer/Program.cs, examples/UserAgentServer/UserAgentServer.csproj, examples/sipcmdline/Program.cs, examples/sipcmdline/Properties/launchSettings.json, examples/sipcmdline/sipcmdline.csproj, src/SIPSorcery.csproj, src/core/SIP/Channels/SIPChannel.cs, src/core/SIP/Channels/SIPClientWebSocketChannel.cs, src/core/SIP/Channels/SIPTCPChannel.cs, src/core/SIP/Channels/SIPTLSChannel.cs, src/core/SIP/Channels/SIPUDPChannel.cs, src/core/SIP/Channels/SIPWebSocketChannel.cs, src/core/SIP/SIPConstants.cs, src/core/SIP/SIPEndPoint.cs, src/core/SIP/SIPTransport.cs, src/core/SIP/SIPURI.cs, src/net/RTP/RTPChannel.cs, src/net/RTP/RTPSession.cs, test/Initialise.cs, test/core/SIP/SIPTransportUnitTest.cs
As requested in #115.
Also adds a new option to the SIP transport class to create missing channels on demand. Saves potentially having to manually create a dozen different channels for client scenarios.
=> Adds a new channel for outbound web socket connections

examples/UserAgentClient/Program.cs, examples/UserAgentServer/Program.cs, src/app/SIPUserAgents/SIPClientUserAgent.cs, src/app/SIPUserAgents/SIPNotifierClient.cs, src/app/SIPUserAgents/SIPRegistrationUserAgent.cs, src/app/SIPUserAgents/SIPServerUserAgent.cs, src/app/SIPUserAgents/SIPUserAgent.cs, src/core/SIP/Channels/SIPTCPChannel.cs, src/core/SIP/Channels/SIPTLSChannel.cs, src/core/SIP/SIPTransport.cs, src/core/SIPFunctionDelegates.cs, src/core/SIPTransactions/SIPNonInviteTransaction.cs, src/core/SIPTransactions/SIPTransaction.cs, src/core/SIPTransactions/SIPTransactionEngine.cs, src/core/SIPTransactions/UACInviteTransaction.cs, src/core/SIPTransactions/UASInviteTransaction.cs, src/net/RTCP/RTCPReportPacket.cs, src/net/RTCP/RTCPSenderReport.cs, src/net/RTP/RTPChannel.cs, src/net/RTP/RTPSession.cs, src/sys/Net/NetServices.cs, test/core/SIPTransactions/SIPTransactionEngineUnitTest.cs
Prior to this all send/receives from transaction classes were directed to the `SendReliable` method which are then picked up and actioned by the dedicated thread in the transaction engine.
While this approach works it is not responsive enough in certain cases, specifically sending `100 Trying` responses to `INVITE` requests and sending `ACK` requests for `INVITE` responses. The consequence of the slower is retransmits of the request or response from the remote party. Again while this is not an issue it is not ideal and pollutes diagnostic SIP traces and such.
This PR allows specific actions from the SIP transaction classes to go straight to the transport layer without needing to be handled by the separate transaction engine thread.
=> Extends the TAP (async/await) approach to the SIP Transaction classes

examples/Softphone/SIPSorcery.SoftPhone/Media/AudioChannel.cs
I am not sure why this happens but on my computer if it's set to 80 milliseconds and # of buffers 1.
The audio has a lot of jitter and on windows 10 you see the mic icon by the taskbar blinking away instead of staying solid.
=> Audio input buffer to 40 milliseconds buffers to 2

src/net/DNS/Resolver.cs
This is not directly a bug but in my setup, it is causing issues.
The issue is that my DNS queries come back with an additional OPT pseudo-RR even thought from what it looks like we aren't asking it to. Which causes all DNS queries to never be cached and also it returns null when asked for a lookup.
As per https://en.wikipedia.org/wiki/Extension_mechanisms_for_DNS
> EDNS introduces a single pseudo-RR type: OPT.
>
> As pseudo-RRs, OPT type RRs never appear in any zone file; they exist only in messages, fabricated by the DNS participants.
>
> The mechanism is backward compatible, because older DNS responders ignore any RR of the unknown OPT type in a request and a newer DNS responder never includes an OPT in a response unless there was one in the request. The presence of the OPT in the …
=> Incorrect DNS TTL caching behavior of OPT EDNS0 RR

src/core/SIPTransactions/SIPTransactionEngine.cs, src/sys/TypeExtensions.cs
This PR attempts to reduce the amount of CPU used by `SIPTransactionEngine.ProcessPendingTransactions()`.  In my local test runs, these changes improved the performance noticeably.  See Issue #182 for a more thorough description of the intent.
=> Issue 182 - Fix performance hot spots on sip-txengine thread

examples/SIPCallServer/Program.cs, src/app/SIPAppFunctionDelegates.cs, src/app/SIPUserAgents/SIPClientUserAgent.cs, src/app/SIPUserAgents/SIPUserAgent.cs
Extend SIPCallFailedDelegate to support sipResponde object where it is possible to get it.  Important to get SIP status codes.
Hello, i would aks you accept this commit. It will be very helpfull in some cases where i need do something bysed on SIP status code.
Thank you
=> Extend SIPCallFailedDelegate

src/app/Media/RtpAudioSession.cs
Replaced the sampleIndex variable with the index counter. Otherwise the buffer won't be filled with the correct bytes as the loop is replacing always the same two byes.
=> Silence encoding bug

src/app/SIPUserAgents/SIPRegistrationUserAgent.cs
I changed MAX_REGISTRATION_ATTEMPT_TIMEOUT, REGISTER_FAILURERETRY_INTERVAL, and MAX_REGISTER_ATTEMPTS to be optional parameters instead of constants for SIPRegistrationUserAgent. The class should behave exactly the same as before if the optional parameters aren't specified.
=> Created optional parameters for SIPRegistrationUserAgent.cs

src/core/SIP/Channels/SIPUDPChannel.cs, src/core/SIP/SIPConstants.cs
I noticed large UDP packets were being truncated. Hope this is of use.
=> Updated to handle receiving of larger UDP packets

examples/sipcmdline/Program.cs, examples/sipcmdline/sipcmdline.csproj, examples/sipcmdline/sipcmdline.sln, src/SIPSorcery.csproj, src/app/SIPUserAgents/SIPClientUserAgent.cs, src/app/SIPUserAgents/SIPRegistrationUserAgent.cs, src/core/DNS/SIPDns.cs, src/core/SIP/SIPEndPoint.cs, src/core/SIP/SIPMessageBase.cs, src/core/SIP/SIPTransport.cs, test/integration/core/SIPDnsUnitTest.cs
Adds ability to use a two stage process for SIP DNS lookups. First stage attempts to use the local cache and only if there is a miss will a DNS query be submitted to the network.
Depends on https://github.com/MichaCo/DnsClient.NET/pull/82.
=> Two stage DNS lookups using local cache.

src/core/SIP/SIPConstants.cs, test/unit/core/SIP/SIPURIUnitTest.cs
This treats the tel scheme the same as the sip scheme where
relevant (versus sips). The tel scheme is not used in any
defaults.
Resolves #295
=> Added support for tel scheme

src/app/Media/Sources/AudioExtrasSource.cs
Using encodedSample.Length produces invalid timestamps when sample count is not equal to result array length.
For example I've tried to use uncompressed L16 PCM audio with 2 bytes per sample, and result was distorted audio playback.
=> Fixed invalid durationRtpUnits values, that caused distorted sound

examples/WebRTCExamples/WebRTCExamples.sln, examples/WebRTCExamples/WebRTCReceiver/Program.cs, examples/WebRTCExamples/WebRTCReceiver/WebRTCReceiver.csproj, examples/WebRTCExamples/WebRTCReceiver/captureopts.html, src/SIPSorcery.csproj, src/net/ICE/IceChecklistEntry.cs, src/net/ICE/RtpIceChannel.cs, src/net/RTCP/ReceptionReport.cs, src/net/RTP/MediaStreamTrack.cs, src/net/RTP/RTPChannel.cs, src/net/RTP/RTPSession.cs, src/net/RTP/RtpVideoFramer.cs, test/unit/net/RTCP/ReceptionReportUnitTest.cs
As part of an investigation into supporting 1080p WebRTC video streams two areas of improvement were identified:
- The RTCP reception reports were reporting the wrong loss statistics. This statistic can be used by the remote peer, Chrome makes use of it, to adjust the sending bit rate.
- The `UdpReceiver` class was observed to create a very large call stack when unable to keep up with the UDP packets arriving from the network. The reason for this is the begin/end callback mechanism used. An improvement is after each end receive call check if there is more network data available and if so process it immediately and avoid teh callback.
=> Minor efficiency improvements to RTP/RTCP handling

src/net/RTP/H264PayloadProcessor.cs, src/net/RTP/RTPSession.cs, src/net/RTP/RtpVideoFramer.cs
As discussed in #378. This PR allows H264 video streams from a remote peer to be de-packetised and combined into encoded H264 video frames.
Thanks to @rafcsoares.
=> Adds H264 depacketisation logic

src/net/SDP/SDP.cs, src/net/SDP/SDPMediaAnnouncement.cs, test/unit/net/SDP/SDPUnitTests.cs
I have a requirement to specify the "i" field for media sessions and documented in [RFC4566](https://tools.ietf.org/html/rfc4566#page-12)
I couldn't find a good place to put a unit test for the SDPMediaAnnouncement.ToString() change. So please point me in the right direction if you have an idea for that.
=> Add description for media streams

src/core/SIP/SIPTransport.cs
When parsing a sip message the SipTransport was passing in the UTF8 decoded messsge, instead of the raw buffer. This caused data loss when the buffer contained non-UTF8 encoded data (as used in mcdata messages).
=> Fix data loss when body contains non-UTF8 data

src/net/STUN/STUNServer.cs
The stun client code is using XORMappedAddress , while the STUNServer.cs return MappedAddress only
Fix this compatible issue by adding XORMappedAddress header to STUNServer.cs
=> Make compatible with the client code

src/net/DtlsSrtp/DtlsSrtpClient.cs, src/net/DtlsSrtp/DtlsSrtpServer.cs, src/net/WebRTC/IRTCPeerConnection.cs, src/net/WebRTC/RTCPeerConnection.cs
This Pull request fix problems when trying to Handshake versus MCU Media Server without support to ExtendedMasterKey like Kurento ... it already fix problems with handshake vs some browsers (Firefox 68/Edge)
The new Property ForceUseExtendedMasterSecret in DtlsStrpServer/DtlsSrtpClient can be used to revert to old behaviour forcing use of ExtendedMasterKey in DtlsHandshake when value is true.
By default this option has value of false, adding support to Kurento and some versions of firefox/edge
=> * Added support to Ignore ExtendedMasterKey in DTLS-SRTP HandShake (Kurento Support)

src/net/SCTP/SctpAssociation.cs, src/net/SCTP/SctpDataSender.cs, src/net/WebRTC/RTCDataChannel.cs
This change implements `RTCDataChannel.bufferedAmount`, where buffered amount is determined by summing the queued data in  the underlying `SctpDataSender`.
=> Implement `RTCDataChannel.bufferedAmount`.

src/net/SCTP/SctpDataSender.cs
A couple places in `SctpDataSender` are calling `ContainsKey` followed by getting the item in a separate call.
However, the item is not guaranteed to still be in the dictionary after the first check.
This change replaces the checking and getting with an atomic `TryGetValue` call.
=> Replace ContainsKey with TryGetValue in SctpDataSender.

src/SIPSorcery.csproj, src/app/SIPUserAgents/SIPClientUserAgent.cs, src/app/SIPUserAgents/SIPServerUserAgent.cs, src/app/SIPUserAgents/SIPUserAgent.cs
Fixes #477
These changes make use of the Client/Server UserAgent Hangup code to enable resend of the BYE with the necessary authentication headers.
Took advantage of the ISIPAccount interface which the server agent already optionally received to propagate the username/password
Added IsHangingUp to both Client/Server UserAgent in order to help the SIPUserAgent get the proper information 
Removed the m_byeTransaction from the SIPUserAgent since it is not needed anymore
=> Resent BYE with auth upon 407 challenge

src/SIPSorcery.csproj, src/app/SIPUserAgents/Behaviours/SIPAuthChallenge.cs, src/app/SIPUserAgents/SIPClientUserAgent.cs, src/app/SIPUserAgents/SIPServerUserAgent.cs, src/app/SIPUserAgents/SIPUserAgent.cs
This simply adds the necessary logic to create an invite message if the user agent receives a 407 during a hold/unhold
=> Re-invite with auth when holding/unholding

src/net/RTP/MediaStreamTrack.cs, src/net/RTP/RTPSession.cs
Pull Request for issue #484.
I'm not sure if it is OK to remove to public property SeqNum; but since none of the examples explicitly use it and I don't really see a usecase for accessing this property other than in the RTPSession class, I removed it.
=> Fixed race-condition in RTP SeqNum generation. Resolves #484.

src/app/SIPUserAgents/SIPRegistrationUserAgent.cs
I am trying to conform to a specification where our SIP client is supposed to refresh within a certain percentage of the expires time returned by the server. I've added the ability for the user of the library to override the behaviour in the SipRegistrationUserAgent and specify the refresh period it desires.
=> Optionally override refresh period for SIPRegistrationUserAgent

src/net/RTP/MediaStreamTrack.cs
Working with a proprietary protocol built over SIP that uses the SSRC in a meaningful way, so I had to remove the `internal` access modifier in order to change it as specified by the protocol. 
**Warning**
Be careful that the RTP Synchronisation Source header field should not be changed unless specific implementations require it. By default this value is chosen randomly, with the intent that no two synchronization sources within the same RTP session will have the same SSRC.
=> Changed SyncSource setter access modifier, see Issue #494

src/core/SIPTransactions/SIPNonInviteTransaction.cs, src/core/SIPTransactions/SIPTransaction.cs, src/core/SIPTransactions/UACInviteTransaction.cs, src/core/SIPTransactions/UASInviteTransaction.cs, test/integration/core/SIPDnsUnitTest.cs, test/unit/core/SIPTransactions/SIPTransactionEngineUnitTest.cs
#520 highlights that SIP transaction classes were not using, and don't need, the transaction request received events and handlers. This PR removes the redundant logic.
Transactions are only ever created by supplying a SIP request to a constructor. There is no need to have a separate method to pass a SIP request to a transaction instance.
=> Remove redundant Tx Request Received events and handlers

src/core/SIP/SIPConstants.cs
Added "siprec" as a known SIPExtension, so that sipsorcery can be used as a SIPREC Server.
=> added siprec as known SIPExtension

src/net/ICE/RtpIceChannel.cs, src/net/RTP/RTPSession.cs, src/net/WebRTC/RTCPeerConnection.cs, src/sys/Net/NetServices.cs
Create PeerConnection with specified udp ports (for webRTC).
If deploying webRTC service to online servers, we have to specify udp ports for PeerConnection from online server side, since there are network/port limits there.
No new test failures imported.
=> Specify udp ports for PeerConnection

src/core/SIPTransactions/SIPTransactionEngine.cs
As discussed in #520 there is a problem if SIP retransmits have been disabled and a DNS result has not been cached. This PR adds a small fix to force a SIP send to wait for the DNS lookup if transaction retransmits have been disabled.
=> Forces DNS to wait sending SIP messages with retransmits disabled

src/core/SIPTransactions/SIPTransactionEngine.cs
I think we need this additional change to fully address the DisableRetransmit issue
=> Force DNS to wait sending Final Response with retransmits disabled

src/net/RTP/MediaStreamTrack.cs, src/net/RTP/RTPSession.cs, src/net/SDP/SDPMediaAnnouncement.cs, src/net/WebRTC/RTCPeerConnection.cs
* This PulRequest add a basic initial support to Renegotiation Logic.
Take a note relative to Event "onnegotiationneeded" because in JavaScript this event is called after "process.nextTick()"
As in pure c# we don't have the same concept of "Process", as Process inself act as a "GameLoop" I created a new Task to emit this event after user AddTrack/RemoveTrack.... This way user can change multiple tracks before event get fired, but the drawback of doing this is because the onnegotiationneeded will be fired in another thread, so the user need to take care about multi-thread access in objects.
=> * Add initial support to Renegotiation Logic

src/net/RTP/Packetisation/H264Depacketiser.cs
I encountered issue with sequence "warp around" during rebuilding fragmented H264 NAL - as parts were incorrectly sorted due to sequence change {65534,65535,0,1} were sorted as {0,1,65534,65535} leading to invalid frame reconstruction.
The above change in the code fixes this for me
PS: I used 2000 as the max number of fragments in the fragmented frame to detect
=> Fix support for rtp sequence wraparound (65535 > 0) in H264 reconstruction

src/core/SIP/SIPHeader.cs
While writing tests for some issues with the Server header, it turned out that the SIPHeader class does not deserialize the Server header field properly (it just doesn't). 
I don't know if that was on purpose since the field itself is not something I want to use since it leaks information, but if not, let's fix it.
The current behaviour will put the Server header key+value into the Unknown headers list
=> Add Server header value for deserialization

test/unit/core/SIP/SIPHeaderUnitTest.cs
This adds a unit test for the previous PR #561 
Verifies that deserializing a SIP Header with the Server field will actually put it into the Server member of the SIPHeader type and not into UnknownHeaders
=> Add Server header unittests

src/net/WebRTC/IRTCPeerConnection.cs
In order for a third party app to be built around the RTCPeerConnection, I aim to leverage the interface to inject behaviors throught Mocks. In order to do so, I need a public accessible interface.
Is this acceptable ?
=> expose peer connection interface

src/app/Media/Sources/AudioExtrasSource.cs, src/app/SIPUserAgents/SIPUserAgent.cs
SIPUserAgent - 
Whilst doing periodic calls of 25 second duration every minute, we were getting intermittent exceptions on event callbacks. Typically, the cause was the m_uac class variable being null at the time of the callback.
There was also an incident where during InitiateCallAsync, m_uac became null. The only explanation being that a late BYE from the SIP provider to the previous call was received during the call setup for the new call. I changed CallEnded to not set m_uac = null, and this has been tested for 100 hours (6000+ calls) without any issues observed.
=> Testing calling against remote SIP provider - Fixes.

src/net/RTP/RTPSession.cs, src/net/SDP/SDP.cs, src/net/WebRTC/RTCPeerConnection.cs, test/integration/core/SIPTransportIntegrationTest.cs, test/integration/net/WebRTC/RTCPeerConnectionUnitTest.cs
Related to issue #609 
This will keep the same media identifier tag specified from the offer into the generated answer.
Previous behavior implied an index based only identification. This caused issues when offer had none indexed tags such as "a=group:BUNDLE audioTag videoTag applicationTag0 applicationTag1" for which sipsorcery would show those tracks in a response similar to "a=group:BUNDLE 0 1 2 3".
=> Replicate mediaid tags for generated answer

src/app/SIPUserAgents/SIPClientUserAgent.cs, src/app/SIPUserAgents/SIPNonInviteClientUserAgent.cs, src/app/SIPUserAgents/SIPRegistrationUserAgent.cs, src/app/SIPUserAgents/SIPUserAgent.cs, src/core/SIP/SIPConstants.cs, src/core/SIPTransactions/UASInviteTransaction.cs
I want to be able to see in network traces the version of the application that is using sipsorcery. This is important because there might be a new version of the application using sipsorcery which changes some behavior but the underlying sipsorcery version stays the same.
I added a setter to SIPConstants.SIP_USERAGENT_STRING and replaced all static readonly field usages with direct references to SIPConstants.SIP_USERAGENT_STRING.
Beacause this is now not really a constant, I renamed the property to SIPConstants.SipUserAgentVersionString.
=> added ability to specify the value for the UserAgent and Server SIP Header

src/core/SIP/Channels/SIPTLSChannel.cs
While testing with TLS and SRTP against a innovaphone PBX, I found the need to be able to provide a client certificate.
otherwise the PBX will not continue with the TLS connection.
Even though in most scenarios, the server and client certificate in use will probably be the same, I left that to the caller of the SIPTLSChannel. There might be some corner cases, where different and/or multiple client certificates are preferrable.
=> ClientCertificates: X509Certificate2Collection for TLS connections

src/net/RTP/RTPChannel.cs, src/net/RTP/RTPSession.cs, src/net/RTP/RTPSessionConfig.cs, src/net/SCTP/SctpUdpTransport.cs, src/sys/Net/NetServices.cs, src/sys/Net/PortRange.cs, test/integration/net/ICE/MockTurnServer.cs, test/unit/sys/net/NetServicesUnitTest.cs, test/unit/sys/net/PortRangeUnitTest.cs
implements #461 
I was not sure, where the state of the already allocated ports/the next port should live. I chose RTPSession, because my usecase has different connected SIP-Enpoints each with their own RTP-Port range. 
For example ports 6000-7999 should be used with PBX 1 and Ports 8000-10000 should be used with a different PBX. RTPSession seemd to be a good place.
I can move it, if there is a better suited place.
I could not test SctpUdpTransport.cs, because I do not have the infrastructure for that. Should Icreate a second CreateRtpSocket overload instead of reusing the existing methods to avoid having to change SctpUdpTransport?
Regards,
Tobias
=> Allow RTP port range to be specified when creating an RTPSession

src/app/SIPUserAgents/SIPNotifierClient.cs, src/app/SIPUserAgents/SIPRegistrationUserAgent.cs, src/core/SIP/SIPHeader.cs
Changes attached.
Two notes: I have actually found a spot where 2^31 -1 is demanded as value for the Expires field, I have attached the reference in the commit message.
The change in SIPNotifierClient.StartSubscription:
It is quite clumsy and actually not correct in terms of total waiting time.
I thought it wouldn't be worth the effort to make things more complicated than necessary.
=> Change for #639: Changing SIPHeader fields Expire and Min-Expire

src/net/WebRTC/RTCPeerConnection.cs
Hi,
As per #650, I've modified RTCPeerConnection IceConnectionStateChange() to set ForceUseExtendedMasterSecret based on the config param when the dtlsHandle creates a DtlsSrtpClient (i.e. when ICE role is active). 
I've just kept the existing short hand ? : notation even though it's quite long a statement now. Let me know if you'd prefer an if statement for readability.
Found this to cause issues when connecting to [Sipwise/RTPEngine](https://github.com/sipwise/rtpengine), it doesn't look to support extended master passwords and was throwing a TLSFatalAlert from the bouncy castle code. Have tested this change which fixes it.
Cheers,
Ali.
=> Allow disabling of extended master password when RTCPeerConnection creates a DTLS client and is set by config. (#650)

src/net/DtlsSrtp/RtpSecureContextCollection.cs, src/net/DtlsSrtp/SecureContextCollection.cs, src/net/DtlsSrtp/SrtpHandlerCollection.cs, src/net/RTP/RTPSession.cs, src/net/SDP/SDPTypes.cs, src/net/WebRTC/RTCPeerConnection.cs
When using SRTP with audio and video, the last media announcement will be the only one to work. 
This for example will cause video to work but not audio, although the negotiation was done for both types individually
The issue arises because of the SRTP handler being agnostic of the media type, and being reconfigured by both media types
This fixes that by replacing the singular srtp handler by a collection that maps a handler by media type.
These are then used to create secure contexts which are used upon receiving or sending rtp packets
=> Proposal fix for SRTP not working with multiple media types in the RTP Session

src/net/RTP/RTPSession.cs
The sample period should be configurable as I see many telephone providers use 20ms and not the default of 50ms specified in RFC2833.
=> Make sample period available as an optional parameter to SendDtmfEvent

src/net/RTP/RTPSession.cs
When sending a DTMF event the timestamp of the audio track does not increment. Correctly the timestamp should be incremented by the duration of the DTMF event.
=> Fix timestamp not incremented after sending DTMF event

src/net/WebRTC/RTCDataChannel.cs, src/net/WebRTC/RTCDataChannelCollection.cs, src/net/WebRTC/RTCPeerConnection.cs
When a new SCTP data frame is received by the `RTCPeerConnection` at the same time as a new data channel is being opened, an exception occurs, because collection of type `List<RTCDataChannel>` is not thread-safe and cannot be changed and enumerated simultaneously.
Additionally, the following things have been improved:
- Data channels are removed from the collection when closed
- New data channel ID generation is also thread-safe now
- Minimized the chance of running out of available data channel IDs
- `RTCDataChannel.onclose` event was not fired from its `close()` method
Worth to mention, that this pull request introduces two breaking changes to the public API:
- The old `RTCPeerConnection.DataChannels` property was of type `List<RTCDataChannel>` and now is of type …
=> Thread-safe RTCDataChannel collection

src/net/ICE/IRTCIceCandidate.cs, src/net/SDP/SDP.cs, src/net/WebRTC/RTCPeerConnection.cs
If there are two agents one with full ICE implementation and one with lite ICE implementation, then the full implementation agent should be always controlling peer
Based on https://datatracker.ietf.org/doc/html/rfc8445#section-6.1.1 and https://datatracker.ietf.org/doc/html/rfc8839#section-4.2.1.4
=> Controlled/controlling is set based on ICE implementation

src/net/ICE/RtpIceChannel.cs
When the nominated local ICE candidate is of 'host' type but the active ICE server is a TURN server, a `NullReferenceException` is thrown when accessing the properties of `NominatedEntry.LocalCandidate.IceServer`.
I assume that the correct behavior would be to just stop the timer, since TURN is not used in this case.
=> Stop TURN refresh when host ICE candidate was nominated

src/net/WebRTC/RTCDataChannel.cs
The use of non-short-circuit logic in a boolean context is likely a mistake - one that could cause serious program errors as conditions are evaluated under the wrong circumstances.
=> SonarQube alert fix

src/net/RTP/MediaStreamTrack.cs, src/net/RTP/Ntp64Timestamp.cs, src/net/RTP/RTPHeader.cs, src/net/RTP/RTPHeaderExtension.cs, src/net/RTP/RTPReorderBuffer.cs, src/net/RTP/RTPSession.cs, src/net/SDP/SDP.cs, src/net/SDP/SDPMediaAnnouncement.cs, test/unit/net/RTP/Ntp64TimestampUnitTest.cs, test/unit/net/RTP/RTPHeaderExtensionUnitTest.cs, test/unit/net/RTP/RTPHeaderUnitTest.cs, test/unit/net/RTP/ReorderBufferUnitTest.cs
I added support for abs-capture-time RTP header extension. It enables us to know when exactly was media captured. Based on
https://webrtc.googlesource.com/src/+/refs/heads/main/docs/native-code/rtp-hdrext/abs-capture-time
Then I added reorder buffer into RTPSession. When reorder happened to RTP packet with Mark set in RTP header, then during decoding some artifacts shows. Now there is reorder buffer which wait specified time for packet with right sequential number.
I also added small refactor of OnReceive method inside RTPSession method. Because there were a lot of duplicate code and the refactor made easier for me to add reorder buffer feature. 
There are unit tests for all added functionality. Also tested with real connection with another peer.
I hope it make sense also to you to …
=> Add support for abs capture time and reorder buffer

src/net/ICE/RtpIceChannel.cs
It will crash frequently in Linux(.Net6) caused by NullReferenceException, but never in windows(.Net6). So I guess the root cause is .Net6 runtime in Linux. I just do a minor change to fix it.
More details below:
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
at SIPSorcery.Net.RtpIceChannel.RefreshTurn(Object state)
at System.Threading.TimerQueueTimer.<>c.<.cctor>b__27_0(Object state)
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
at System.Threading.TimerQueueTimer.CallCallback(Boolean isThreadPool)
at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
at …
=> fix crash due to NullReferenceException

src/net/RTP/RTPSession.cs
Fixed issue discovered by @ChristopheI
details at #690
=> bugfix: RTP video frame are now processed even without used buffers

src/net/RTP/RTPSession.cs
Hello!
Pretty sure it is a typo error. There was double `mediaType == SDPMediaTypesEnum.audio` check in `SendRtcpFeedback`
=> Fix typo in SendRtcpFeedback

src/app/SIPUserAgents/SIPRegistrationUserAgent.cs
Hello, I've noticed some bug, here is a fix:
There will be NullReferenceException if we call `Stop` on `SIPRegistrationUserAgent` without calling `Start`:
```
[sipsorcery:Error][T43] Exception SIPRegistrationUserAgent Stop. System.NullReferenceException: Object reference not set to an instance of an object.
at SIPSorcery.SIP.App.SIPRegistrationUserAgent.Stop(Boolean sendZeroExpiryRegister) in /_/src/app/SIPUserAgents/SIPRegistrationUserAgent.cs:line 310 
```
There is a check for `m_exit` flag, but default value is `false`. So this method will try to stop registration agent even it was not started
Probably related to https://github.com/sipsorcery-org/sipsorcery/issues/737
=> Prevent NullReferenceException on SIPRegistrationUserAgent.Stop

src/net/RTCP/RTCPSession.cs
Hello, I try to estimate QoS of webrtc communication and find RTT(round-trip time) and jitter might be incorrect. I update these per my understanding for https://datatracker.ietf.org/doc/html/rfc3550.
Please correct me if I am worng, thanks!
=> Fix Issue in Sender Report RTCP Packet

src/net/SCTP/SctpDataSender.cs, test/unit/net/SCTP/SctpDataSendRecvUnitTest.cs, test/unit/net/SCTP/SctpDataSenderUnitTest.cs
Finishing off the TODO in the code. 
Helps avoid resending the same unconfirmed chunk(s) repeatedly when latency is present.
=> Implement round trip measurement for SCTP

src/net/WebRTC/RTCDataChannel.cs, src/net/WebRTC/RTCPeerConnection.cs
This now allows for creating a data channel that is negotiated out of band. Prior to this, the DCEP messages were being sent which the other side will not expect and will most likely fail.
=> Respect RTCDataChannelInit negotiated setting when opening data channel

src/net/WebRTC/IRTCDataChannel.cs, src/net/WebRTC/RTCDataChannel.cs, test/unit/net/SCTP/SctpDataSendRecvUnitTest.cs
This PR fixes a breaking bug from https://github.com/sipsorcery-org/sipsorcery/pull/783 where datachannels were initialized with Id "0" when unspecified instead of "null".
It also applies the correct default values for[ `RTCDataChannelInit`](https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/createDataChannel)
=> Fix datachannel initialization

src/net/SCTP/SctpDataSender.cs
In real-world high-throughput scenarios and testing with [clumsy](https://jagt.github.io/clumsy) we've been running into an issue where the SCTP sender would get stuck repeatedly sending duplicate TSNs. 
Due to the trouble in isolating the exact cause I suspect this is due to a concurrency issue in the sender class where `_unconfirmedChunks` and/or `_missingChunks` are not correctly removed following a `SACK`. It is easy to repeat by increasing the lossy scenarios with clumsy, but difficult to repeat with low throughput or stable network conditions.
Rather than affecting performance with the addition of thread locks, this simple solution responds to the already included `SctpSackChunk.DuplicateTSN` reports to clean out the chunk dictionaries and resolves this issue.
=> SCTP fix duplicate TSNs being resent

src/core/SIP/SIPResponse.cs, test/unit/core/SIP/SIPResponseUnitTest.cs
Fix a bug where SipResponse.Copy did not copy the message body
=> SIPResponse.Copy copies body

src/core/SIP/SIPTransport.cs, src/core/SIPTransactions/SIPTransactionEngine.cs
Hello!
Commit https://github.com/sipsorcery-org/sipsorcery/commit/efcbba2c35b887660b9985b739823a70623bb136 introduced memory leak: an AutoResetEvent object was not freed. Here is a fix
=> Fix memory leak in SIPTransactionEngine

src/core/SIP/SIPConstants.cs
Such as described in https://datatracker.ietf.org/doc/html/rfc5031 URI can start with urn: which acts exactly like other URIs but with known words.
=> Enable parsing SIP packets using RFC5031 URI starting with urn: 

src/core/SIPTransactions/SIPTransactionEngine.cs
Hello, in PR https://github.com/sipsorcery-org/sipsorcery/pull/794 I've introduced ObjectDisposedException, as @DavidMartynWood noticed. So there is a draft that can improve the situation.
Is it ok, if we replace Thread created by ThreadPool (Task.Factory.StartNew) with native thread, that can be joined synchronously?
@sipsorcery, of course if you don't mind waiting a bit for transaction polling thread to complete.
In my scenario application creates many instances of SIPTransport and can free any of them at any time. That's why I care about memory leaks and proper dispose of SIPTransport
If it conflicts with vision of SIPSorcery library, then ok, I can maintain a fork with this kind of behaviour. But part which checks if TransactionEngine was disposed at AddTransaction can be handy …
=> Join transaction polling thread: fix ObjectDisposedException

src/app/SIPUserAgents/SIPUserAgent.cs
Allowing passing on username and password during BlindTransfer in case there's a proxy authentication required.
=> Fixed blind transfer authentication

src/core/SIP/SIPHeader.cs
1. Correct protocol encoding when using custom ``SIPAuthenticationHeader.Value`` to construct ``SIPMessage`` and ``SIPResponse``
2. Fix protocol construct adding unexpected empty line when ``SIPAuthenticationHeader.Value=null``
sample code
```csharp
var sip = new SIPRequest(SIPMethodsEnum.REGISTER, new SIPURI("34020000002000000001", "192.168.1.2:7100", string.Empty, SIPSchemesEnum.sip));
var sipUri = new SIPURI("130909113319427420", "192.168.1.100:7100", string.Empty, SIPSchemesEnum.sip);
sip.Header ??=
new SIPHeader(
new SIPFromHeader(null, sipUri, "3806746264"),
new SIPToHeader(null, sipUri, ""), 1, "1263125095");
sip.Header.CSeqMethod = SIPMethodsEnum.REGISTER;
sip.Header.Vias = new SIPViaSet();
sip.Header.Vias.AddBottomViaHeader(new SIPViaHeader(new SIPEndPoint(SIPProtocolsEnum.udp, …
```
=> Correctly construct custom SIPAuthenticationHeader

src/net/RTP/MediaStream.cs
Bug in this commit https://github.com/sipsorcery-org/sipsorcery/commit/aa08d2a54f4caedc6cb026e354b23eaf56cc5613#diff-af18cb9a6a993dec0359f2d409de3cbe60b0f3eddd13e293f7fdd91e648e7957R489
RemoteTrack can be null and then you receive exception:
```
Exception UdpReceiver.EndReceiveFrom. System.NullReferenceException: Object reference not set to an instance of an object.
at SIPSorcery.net.RTP.MediaStream.OnReceiveRTPPacket(RTPHeader hdr, Int32 localPort, IPEndPoint remoteEndPoint, Byte[] buffer, VideoStream videoStream)
at SIPSorcery.Net.UdpReceiver.EndReceiveFrom(IAsyncResult ar)
```
=> nullable object

src/app/SIPUserAgents/SIPRegistrationUserAgent.cs
I've encountered a SIP provider that despite giving an OK response to a SIP registration will not send invites unless the username is added in the Contact header. I noticed that MicroSIP always sends this username, but in order not to potentially break anything for others I've turned this feature off by default.
=> Allow for optional adding of username in the Contact header during registration

src/SIPSorcery.csproj, src/sys/Net/NetServices.cs
Workaround for .NET 6 issue 75809: https://github.com/dotnet/runtime/issues/75809
This produces a crash when using SipSorcery on Android devices, as the retrieval of all network interfaces creates an internal crash.
=> Fix crash when using SipSorcery in Android devices.

src/app/SIPUserAgents/SIPRegistrationUserAgent.cs
Causing reregistration synchronisation problems. Fix issue where uninitialized contactURI (0.0.0.0:0) was used to compare against the contact uri of the response. Instead use the Request.Header.Contact.ContactURI to compare with.
=> Register response containing expiry value is not always recognized.

src/net/WebRTC/RTCPeerConnection.cs
This fix is to remove the RTCPeerConnection's check if the SCTP transport is in the connected state and to close it anyways. Internally the SCTP class does that check. 
This has the effect of removing a nasty bug where after a WebRTC connection is closed, CPU usage spikes since the SCTP transport never gets the private `_isClosed` set to true and loops forever without limitations in the receive thread
=> Remove state check

src/net/RTP/RTPSession.cs
Fix: Previously, when multiple tracks of one type(audio/video) were active and none of the other.
GetMediaStream(uint) would return wrong mediastreams.
https://github.com/sipsorcery-org/sipsorcery/issues/898
=> GetMediaStream(uint) works with multiple streams

src/app/SIPUserAgents/SIPUserAgent.cs
Proposed solution will not HangUp the call when its placed on hold or remote party has put us on hold. 
After receiving a timeout while call is on hold and taking call off from hold the media session continues to work properly.
=> Add fix for the following issue: #884

src/core/SIP/Channels/SIPStreamConnection.cs, src/core/SIP/Channels/SIPStreamWrapper.cs, src/core/SIP/Channels/SIPTLSChannel.cs
The workaround has been proven to work in production.
When using SIP/TLS on an incoming call, RINGING after TRYING may not be sent over the network. Instead, the following exception occurs:
```
System.NotSupportedException: The BeginWrite method cannot be called when another write operation is pending.
   at System.Net.Security._SslStream.ProcessWrite(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security._SslStream.BeginWrite(Byte[] buffer, Int32 offset, Int32 count, AsyncCallback asyncCallback, Object asyncState)
   at System.IO.Stream.<>c.<BeginEndWriteAsync>b__53_0(Stream stream, ReadWriteParameters args, AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrim[TInstance,TArgs](TInstance thisRef, …
```
=> Fix SIP/TLS RINGING not sent after TRYING (#889)

src/net/SCTP/SctpDataSender.cs, test/unit/net/SCTP/SctpDataSendRecvUnitTest.cs, test/unit/net/SCTP/SctpDataSenderUnitTest.cs
I found that in some real-world high-throughput scenarios with 'normal' packet disruption (i.e. sending chunked files) DataChannels would appear to hang but network usage would be very high (and no errors reported). This was caused by sending the wrong 'missing' chunks. 
This PR implements [`RFC4960 7.2.4 Fast Retransmit on Gap Reports`](https://www.rfc-editor.org/rfc/rfc4960#section-7.2.4) to resolve this.
In addition:
- Chunk acknowledgement during gap report processing (i.e. chunks that don't advance the cumulative ack TSN but have been received) so these are not retransmitted in place of other needed chunks.
- Don't send new chunks when `cwnd` is 0 (rfc4960 6.1)
- Tests updated accordingly
=> RFC4960 7.2.4 SCTP Fast Recovery

src/SIPSorcery.csproj, src/core/SIP/SIPEndPoint.cs, src/core/SIP/SIPTransport.cs
In the previous code, due to the order of logical condition checks in if, the code in else will never be executed
=> Fix dead code in SendRequestAsync and SendResponseAsync

src/core/SIP/SIPUserField.cs
Hello,
I have identified and resolved an issue related to the parsing of names in the context of certain switches/PBX systems. Specifically, these systems sometimes insert angle brackets (<>) into the name portion of their headers, as demonstrated in the following example:
From: "<00412222222>" <sip:00412222222@xyz.example.com;user=phone>;tag=1111-XX-111111-22222
In the current implementation, our parsing logic fails to handle this format correctly.
With the changes proposed in this pull request, our parser has been updated to properly handle such cases. The updated logic now correctly identifies and processes names, even when they're encapsulated within angle brackets.
Please review the changes and let me know if you have any feedback or require any further modifications. I look forward …
=> Fix reading of From or PAI if <> is used in name

src/net/RTCP/RTCPCompoundPacket.cs, test/unit/net/RTP/RTPHeaderUnitTest.cs
Hello!
Commit https://github.com/sipsorcery-org/sipsorcery/commit/65e444557fa186b2c932f2e53966283555903fc5 introduces null-coalescing operator, which is not supported in default language version of project
This also should fix failing github action:
=> Replace null coalescing operator with simple if

Directory.Build.props
When I checked out repo locally I have a problem with building with `dotnet build` because LanguageVersion for net461 is 7.3.  
```
\src\net\RTCP\RTCPCompoundPacket.cs(161,32): error CS8370
```
This PR bumps language version to 8.0 for net461 builds
=> LangVersion for net461

src/app/SIPUserAgents/SIPCallDescriptor.cs
Corrected 'teh' to 'the' in SIPCallDiscriptor constructor summary.
=> Update to spelling in SIPCallDescriptor.cs constructor

src/net/RTCP/ReceptionReport.cs
Fixing DelaySinceLastSenderReport not set and overriding LastSenderReportTimestamp with DelaySinceLastSenderReport when ReceptionReportSample packet is being parsed as Big Endian.
I cam across this when I was checking how the Reception Report Sample is being parsed from the packet.
=> Fixing DelaySinceLastSenderReport being overriden

src/net/RTP/MediaStream.cs, src/net/RTP/RTPSession.cs
For cases that do not involve the media being generated locally it is requires that the sequence number be passed along correctly to client connections.
Currently Sipsorcery auto generates sequence numbers when SendRtpRaw is called. 
An example of this is a WebRtc media server. If you mark sequential sequence numbers for packets that are not actually sequential it results in distortion on the client side. The client needs to be aware of packets that were lost on the way to the server.
I have added an additional implementation of SendRtpRaw that includes a sequence number. I have attempted to keep the existing methods the same as to not make breaking changes.
Thanks for all the hard work on this project!
=> Add ability to set sequence number for cases where sequence number is not generated locally.

src/app/Media/VoIPMediaSession.cs
Previously, only the AudioSource start and close were called, this was working with the current implementation of WindowsAudioEndpoint which grouped audiosink and source in the audiosource methods, but this does not work if only the audiosink is used. This requires also a change in WindowsAudioEndpoint were the code for the audiosink is moved at the right place (the placeholders do exist but are empty)
I'll suggest also a pull request for the changes to bring into the other repository (WindowsAudioEndpoint). This current request does not affect the behaviour as current WindowsAudioEndpoint implementation provides empty placeholders for the fucntions calls added by this commit.
=> Call AudioSink and AudioSource start/close methods

src/app/SIPUserAgents/SIPUserAgent.cs
Explicitly disposing a SIPUserAgent after a failed call attempt as it attempts to execute the CallEnded() method from within the ClientCallAnsweredHandler() method can result in attempting to Release() an already disposed SemaphoreSlim instance. This can occur because the ClientCallFailed event handler is invoked before executing the CallEnded() method. This scenario throws an uncaught ObjectDisposedException which can bring down the entire application.
This commit wraps all SemaphoreSlim.Release() calls within SIPUserAgent in a try/catch block to swallow the ObjectDisposedException to avoid potentially crashing the application.
=> Safely release SIP user agent semaphore

src/app/Media/VoIPMediaSession.cs
When using the VoIPMediaSession class the VideoFormatsNegotiated event handler does not pass along the negotiated video format to the video test pattern source. As a result the video test pattern source would always use VP8 even if H264 was the negotiated format.
=> Pass negotiated video format to video test pattern source

src/app/Media/Codecs/AudioEncoder.cs, src/app/Media/Codecs/PcmResampler.cs, src/app/Media/Sources/AudioExtrasSource.cs, src/app/Media/VoIPMediaSession.cs, src/app/Media/VoIPMediaSessionConfig.cs
Currently audio extras in `VoIPMediaSession` use `AudioEncoder` for encoding audio extras. It leads to problems if we are using custom encoder: `AudioEncoder.EncodeAudio` method throws an exception because of unsupported audio format. So we need a way to inject a custom encoder for `VoIPMediaSession` audio extras.
=> Pass encoder to VoIPMediaSession audio extras

src/net/WebRTC/RTCPeerConnection.cs
Like Audio and/or Video Streams, when the the RTCPeerConnection is closed, existing DataChannels are also closed
Related to #1058
=> When RTCPeerConnection is closed, we also close DataChannels

test/integration/net/WebRTC/RTCPeerConnectionUnitTest.cs, test/unit/net/RTP/RTPSessionUnitTest.cs
If remote description is used first, it's normal to use payload id from remote and not ones set locally
=> Fix several unit test (linked to capabilities / payload id)

src/app/SIPUserAgents/SIPUserAgent.cs
The new 'publicIpAddress' argument is optional, so the interface is backward compatible. This allows specifying the public IP address to use in SDP when answering the call, and the UA is behind NAT.
=> Add ability to specify public IP address when answering the call

src/net/RTCP/RTCPFeedback.cs, test/unit/net/RTCP/RTCFeedbackUnitTest.cs
I've found a bug in REMB packet serialisation.
For reference, here's the layout:
```
// 0                   1                   2                   3
// 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
//+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
//|  Unique identifier 'R' 'E' 'M' 'B'                            |
//+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
//|  Num SSRC     | BR Exp    |  BR Mantissa                      |
//+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
//|   SSRC feedback                                               |
```
Based on sample Wireshark dissect:
current code reads mantissa as `..00 0110 0100 0010 0010` (first two bits are always 0)
Made following changes:
* Mantissa is using 2 …
=> REMB - fix serialisation

src/net/RTP/MediaStream.cs, src/net/RTP/RTPHeader.cs, src/net/SDP/SDP.cs, src/net/SDP/SDPAudioVideoMediaFormat.cs, src/net/SDP/SDPMediaAnnouncement.cs, src/net/WebRTC/RTCPeerConnection.cs, test/unit/net/RTP/RTPHeaderExtensionUnitTest.cs
* added `a=extmap:` http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time to SDP extension headers
* added `a=rtcp-fb goog-remb` for all media tracks to SDP
* the header extension is added only when remote track supports it
* for now the method can only accept a single extension to be added, but could be made more generic for subsequent extensions
* fixed typo `ATTRIBUE` in one of the consts
closes #1081
=> Support for abs-send-time - closes #1081

src/app/SIPUserAgents/ISIPServerUserAgent.cs, src/app/SIPUserAgents/SIPB2BUserAgent.cs, src/app/SIPUserAgents/SIPNonInviteServerUserAgent.cs, src/app/SIPUserAgents/SIPServerUserAgent.cs, src/app/SIPUserAgents/SIPUserAgent.cs, src/core/SIP/SIPTransport.cs, src/core/SIPFunctionDelegates.cs, src/core/SIPTransactions/UASInviteTransaction.cs
Introduce a SIPUASCancelDelegate so that reason and other information can be passed to the application when a call is cancelled.
=> Introduce SIPUASCancelDelegate

src/app/SIPUserAgents/SIPRegistrationUserAgent.cs
We need a method to remove `REGISTER` values from the Allow headers of REGISTER requests for our custom Kamailio setup.
=> Customize Allow headers of REGISTER requests

src/net/DtlsSrtp/DtlsSrtpClient.cs, src/net/DtlsSrtp/DtlsSrtpServer.cs
Chrome is now checking certificate type and needs to be passed the correct one in Certificate Request. WebRTC primarily uses ECDSA, I believe the intent is to support ECDSA, per TLS protocol, you need to say so in the CertificateRequest message.
Adding ECDSA to DtlsSrtpClient.cs as just to remain in sync with the server code but I have no way to verify that direction.
Fixes https://github.com/sipsorcery-org/sipsorcery/issues/1104
=> Adding ECDSA as certificate type Fixes #1104

src/app/Media/Sources/AudioExtrasSource.cs
Adding try-catch blocks to timer callbacks to avoid crashing the app when an exception is thrown.
=> Fixed application crash

src/net/SDP/SDP.cs, src/net/SDP/SDPAudioVideoMediaFormat.cs
SDPAudioVideoMediaFormat has 3 WithUpdated methods:
```
public SDPAudioVideoMediaFormat WithUpdatedID(int id, SDPAudioVideoMediaFormat format)
public SDPAudioVideoMediaFormat WithUpdatedRtpmap(string rtpmap, SDPAudioVideoMediaFormat format)
public SDPAudioVideoMediaFormat WithUpdatedFmtp(string fmtp, SDPAudioVideoMediaFormat format)
```
This format parameter would suggest these are static methods, but they are object methods. As such it would make more sense to copy the `this` object.
This is the approach already used on SDPApplicationMediaFormat:
```
public SDPApplicationMediaFormat WithUpdatedID(string id)
public SDPApplicationMediaFormat WithUpdatedRtpmap(string rtpmap)
public SDPApplicationMediaFormat WithUpdatedFmtp(string fmtp)
```
It would make sense to use this interface on both …
=> SDPAudioVideoMediaFormat WithUpdated methods should use current object not a format parameter

src/net/RTP/RTPSession.cs, src/net/SDP/SDP.cs
Using a signed 32-bit integer was ignoring large values seen in the wild such as from RTPEngine (64bit populated by SSL_random) and NTP timestamps which are 64-bit and recommended by the SDP RFC.
=> Increase SDP AnnouncementVersion to an unsigned 64-bit integer.

src/net/ICE/RtpIceChannel.cs, src/net/STUN/STUNAttributes/STUNAddressAttribute.cs, src/net/STUN/STUNAttributes/STUNAddressAttributeBase.cs, src/net/STUN/STUNAttributes/STUNAttribute.cs, src/net/STUN/STUNAttributes/STUNXORAddressAttribute.cs, src/net/STUN/STUNMessage.cs
=> WebRTC IPv6 support for TURN (along with REQUESTED-ADDRESS-FAMILY)

src/app/SIPUserAgents/SIPClientUserAgent.cs, src/app/SIPUserAgents/SIPServerUserAgent.cs
While using SIPClientUserAgent or SIPServerUserAgent, we might need to send Non Invite requests like SIP INFO or SIP NOTIFY
=> uac and uas send NonInvite SIP Request

src/core/SIP/SIPURI.cs, test/unit/core/SIP/SIPURIUnitTest.cs
This PR tweaks `CanonicalAddress` and `ToAOR` behaviour so that tel: URIs can be used similarly to how sip: URIs are.
=> Improved tel: URI handling

src/app/SIPUserAgents/SIPUserAgent.cs
Found a need to modify the call descriptor for the outbound invite initialised by a sip refer.
=> Allow customisation of the call descriptor when transferring calls

src/net/RTP/MediaStream.cs, src/net/RTP/RTPSession.cs
Keep the local track's RTP event capability when setting remote description on an RTP session
=> Keep the local track's RTP event capability when setting remote description on an RTP session (Fix issue-1164)

src/net/RTP/MediaStream.cs, src/net/RTP/MediaStreamTrack.cs, src/net/RTP/RTPHeader.cs, src/net/RTP/RTPHeaderExtension.cs, src/net/RTP/RTPHeaderExtensions/AbsSendTimeExtension.cs, src/net/RTP/RTPHeaderExtensions/AudioLevelExtension.cs, src/net/RTP/RTPHeaderExtensions/CVOExtension.cs, src/net/RTP/RTPSession.cs, src/net/SDP/SDP.cs, src/net/WebRTC/RTCPeerConnection.cs
Three are actually supported:
- Abs Send Time - thanks to @[theimowski](https://github.com/theimowski) with https://github.com/sipsorcery-org/sipsorcery/pull/1084
- Coordination of Video Orientation (CVO)
- Audio Level 
It's "easy" to add new RTP Header Extension:
- needs to inherit from RTPHeaderExtension
- needs to define an URI as public const string which define the extension in the SDP: for example "http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time" for the AbsSendTime extension
By default no extension is used. If you want to use one or more you have to define them when creating a **MediaStreamTrack** with the **headerExtensions** optional parameter.
Example:
```
static private Dictionary<int, RTPHeaderExtension> GetRTPHeaderExtensions(SDPMediaTypesEnum mediaType)
{ …
```
=> RTP Header Extensions

src/net/RTP/MediaStream.cs, src/net/RTP/MediaStreamTrack.cs, src/net/RTP/RTPHeader.cs, src/net/RTP/RTPHeaderExtension.cs, src/net/RTP/RTPHeaderExtensions/AbsSendTimeExtension.cs, src/net/RTP/RTPHeaderExtensions/AudioLevelExtension.cs, src/net/RTP/RTPHeaderExtensions/CVOExtension.cs, src/net/RTP/RTPSession.cs, src/net/SDP/SDP.cs, src/net/WebRTC/RTCPeerConnection.cs, test/integration/net/WebRTC/RTCPeerConnectionUnitTest.cs, test/unit/net/RTP/RTPHeaderExtensionUnitTest.cs
Three are actually supported:
- Abs Send Time - thanks to @[theimowski](https://github.com/theimowski) with https://github.com/sipsorcery-org/sipsorcery/pull/1084
- Coordination of Video Orientation (CVO)
- Audio Level 
It's "easy" to add new RTP Header Extension:
- needs to inherit from RTPHeaderExtension
- needs to define an URI as public const string which define the extension in the SDP: for example "http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time" for the AbsSendTime extension
By default no extension is used. If you want to use one or more you have to define them when creating a **MediaStreamTrack** with the **headerExtensions** optional parameter.
Example:
```
static private Dictionary<int, RTPHeaderExtension> GetRTPHeaderExtensions(SDPMediaTypesEnum mediaType)
{ …
```
=> RTP Header Extensions (with tests)

src/net/DtlsSrtp/DtlsSrtpServer.cs, src/net/DtlsSrtp/DtlsUtils.cs
Alos adds a method for generating an ECDSA compatible certificate for DTLS handshake testing.
=> Added a DTLS diags message

src/net/DtlsSrtp/DtlsSrtpTransport.cs, src/net/DtlsSrtp/SrtpHandler.cs, src/net/DtlsSrtp/Transform/IPackerTransformer.cs, src/net/DtlsSrtp/Transform/RawPacket.cs, src/net/DtlsSrtp/Transform/SrtcpTransformer.cs, src/net/DtlsSrtp/Transform/SrtpTransformer.cs, src/net/ICE/RtpIceChannel.cs, src/net/RTP/MediaStream.cs, src/net/RTP/Packetisation/H264Packetiser.cs, src/net/RTP/RTPChannel.cs, src/net/RTP/RTPHeader.cs, src/net/RTP/RTPPacket.cs, src/net/RTP/VideoStream.cs, src/sys/Crypto/Crypto.cs
Reduce Memory allocations on H264 Sender HotPath by reusing byte[] and using ArrayPool<byte>
=> Reduce Memory allocations

src/core/SIP/SIPTransport.cs
Possible solution for #1169 
Update TopViaHeader for a SIP-Cancel:Ok to assure correct routing of the response back to it's originating socket.
If not done the set via header will be used which might not be correctly routable.
=> Update TopViaHeader for CANCEL:OK possible fix for Issue 1169

src/net/RTP/RTPSession.cs
After setting up logging i noticed a repeating error finding a media stream - not sure why the id is not matching but this logic looked a bit dodgy and the change resolved it with no side effects i could find.
=> fix stream retrieval bug

src/SIPSorcery.csproj, src/app/Media/VoIPMediaSession.cs, src/net/SDP/SDPAudioVideoMediaFormat.cs
A bug had been introduced when the default format, which was created when no match was found, was a normal looking format with an ID of 0. This was a big problem as 0 is PCMU. Added a dedicated method for looking up a format by name so that if no match an explicit empty format can be returned and avoid impersonating PCMU.
=> Fixed selecting the common format when no telephone event.

src/net/ICE/RTCIceCandidate.cs
Adjusted the candidateStr, for the webrtc client to connect to the TURN server using the indicated tcp protocol
=> Fix: Offer tcp aligned to condition (#1294)

src/net/RTCP/RTCPSession.cs
Changed a constant to a publically mutable property so timeouts can be customized for RTP sessions.  This is useful in cases where the VOIP system doesn't send packets if there's silence in the audio stream.
=> Allow customizable timeouts for RTP sessions

src/net/SDP/SDPTypes.cs
The `text` media type is valid per RFC 4566 and is present in the [media registry](https://www.iana.org/assignments/sdp-parameters/sdp-parameters.xhtml#sdp-parameters-1), however, if a message using `m=text` is encountered, an exception is thrown from `SDPMediaTypes.GetSDPMediaType` due to the unrecognized enum field being used.
=> Add missing "text" SDP media type

src/core/CallProperties.cs
There is already the format option "N" in the ToString() method of type Guid to perfom this kind of formatting. This makes the code lighter, and is more performant as it saves string allocations and manipulations.
=> Use "N" formatting option in Guid.ToString() instead of replacing characters

src/core/SIP/SIPConstants.cs, src/net/RTSP/RTSPContants.cs, src/sys/StorageTypes.cs
To parse enums, it is recommended to use TryParse(). This is more C# idiomatic, and it avoids declaring a try/catch block, which has a performance cost.
=> To parse enums, use TryParse() instead of Parse() in a try block.

src/sys/TypeExtensions.cs, test/unit/sys/TypeExtensionsUnitTest.cs
* Use a more idiomatic approach to convert a DateTime to Unix time, and add a unit test.
* Rename the function GetEpoch() to ToUnixTime(), as is this function doesn't
return the epoch, but the number of seconds since the epoch.
* Also add a unit test to make sure this implementation is not subject to the year
2038 problem.
=> Rename and reimplement the Unix time conversion function

src/sys/BufferUtils.cs, test/unit/sys/BufferUtilsUnitTest.cs
Fix a potential IndexOutOfRangeException in BufferUtils.GetStringPosition()
when parameter "find" is an empty string.
If we don't check for the length of parameter "find", then the first indexing of "findArray" raises an IndexOutOfRangeException.
=> Fix a potential IndexOutOfRangeException in BufferUtils.GetStringPosition()

src/sys/TypeExtensions.cs
The current implementation creates `length * 2 + 1` `string`s without separator and `length * 3` `string`s with separator.
The proposed implementation use [`Create<TState>(Int32, TState, SpanAction<Char,TState>)`](https://learn.microsoft.com/en-us/dotnet/api/system.string.create?view=net-9.0#system-string-create-1(system-int32-0-system-buffers-spanaction((system-char-0)))`), where possible, to allocate only the final `string` and an intermediary `byte[]` where not possible.
=> Optimize TypeExtensions.HexStr

src/core/SIP/SIPHeader.cs
Resolves #1339.
The authentication scheme should be checked case-insensitively, as per the following sources (mostly related to HTTP, but the same should apply for SIP):
- [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/WWW-Authenticate)
- [Related Rails issue](https://github.com/rails/rails/issues/21199)
- [RFC 2617](https://datatracker.ietf.org/doc/html/rfc2617#section-1.2) ("It uses an extensible, **case-insensitive** token to identify the authentication scheme") (emphasis mine)
=> Check authentication scheme case-insensitively

src/app/SIPUserAgents/SIPUserAgent.cs
There is an issue in the timeout for ACK responses, resulting in the error:
> The attempt to answer a call failed as the dialog was not created. The likely cause is the ACK not being received in time.
The timeout is set to be T2 (5 seconds), but according to the [RFC](https://www.ietf.org/rfc/rfc3261.txt), it should be higher:
>    layer for transmission.  The ACK MUST be sent to the same address,
>   port, and transport to which the original request was sent.  The
>   client transaction SHOULD start timer D when it enters the
>   "Completed" state, with a value of at least 32 seconds for unreliable
This pull request increases the timeout to T6, i.e. 32 seconds.
=> Increase WAIT_DIALOG_TIMEOUT for ACK to T6

src/app/Media/VoIPMediaSession.cs
I just experienced this scenario today so I replaced `async void` with `async Task` in `TakeOffHold()` to prevent silent failures and ensure exceptions can be awaited and handled correctly.
=> Update TakeOffHold() to Task

examples/OpenAIExamples/WebRTCOpenAI/Program.cs, src/app/Media/Codecs/AudioEncoder.cs
Partially resolves #1399 (update to SIPSorceryMedia.Windows also required).
=> Fix the audio encoder to cope with two channel OPUS samples.

src/net/RTP/Packetisation/H265Depacketiser.cs, src/net/RTP/Packetisation/H265Packetiser.cs, src/net/RTP/VideoStream.cs
I read a bit [RFC 7798 Section 4.4](https://datatracker.ietf.org/doc/html/rfc7798#section-4.4)
Summary:
- The NAL parser forgot to set `zeroes` back to 0,
- The aggregator forgot to return aggregated NALs,
- Use a semantically readable fragmentation NAL (FU) handling
fixes #1392 
forwards https://github.com/sipsorcery-org/SIPSorceryMedia.FFmpeg/pull/97
=> Fix HEVC NAL parsing and RTP de/packetization

src/SIPSorcery.csproj, src/net/STUN/STUNUri.cs, src/sys/Net/IPSocket.cs
This PR introduces two key improvements:
1. **Enforces immutability of `STUNUri`**, because it's used as a key for `Dictionary<TKey, TValue>` and that can cause runtime inconsistencies and subtle bugs.
2. **Replaces `string` createion with `ReadOnlySpan<char>`** for `STUNUri` and `IPSocket` parsing to improve performance and reduce memory allocations.
---
Using mutable objects as keys in a `Dictionary<TKey, TValue>` can lead to unpredictable behavior. The dictionary relies on the key's hash code and equality comparison to locate entries. If a key is mutated after being added:
- Its hash code may change, making it unreachable in the dictionary.
- Lookups, removals, and updates may silently fail.
- It can lead to memory leaks or incorrect data retrieval.
**Example of the issue:**
```csharp …
```
=> Enhance STUNUri-related performance and reliability

src/net/RTP/RTPSession.cs
Fix #1438: Video Stream are cut when, in a same PeeConnection, Video stream are added/removed
Also add missing code in SendRtpRaw() and in SendRtcpTWCCFeedback() when text as MediaType is used
Remove redundancy code
Use same tests for video than ones used for audio or text
=> Fix #1438: Video Stream are cut when, in a same PeeConnection, Video streams are added/removed
