- README.md
> Update Markdown for the appveyor build

- examples/Softphone/SIPSorcery.SoftPhone.sln
- examples/Softphone/SIPSorcery.SoftPhone/App.config
- examples/Softphone/SIPSorcery.SoftPhone/Media/RTPManager.cs
- examples/Softphone/SIPSorcery.SoftPhone/Properties/Resources.Designer.cs
- examples/Softphone/SIPSorcery.SoftPhone/Properties/Settings.Designer.cs
- examples/Softphone/SIPSorcery.SoftPhone/SIPSoftPhoneState.cs
- examples/Softphone/SIPSorcery.SoftPhone/SIPSorcery.SoftPhone.csproj
- examples/Softphone/SIPSorcery.SoftPhone/Signalling/STUNClient.cs
- examples/Softphone/SIPSorcery.SoftPhone/Softphone.xaml
- examples/Softphone/SIPSorcery.SoftPhone/Softphone.xaml.cs
* Fixed building of SIPSorcery.SoftPhone sample
* Rewritten SoftphoneSTUNClient, code cleanup
* Displaying current public IP address in UI
> Softphone sample improvements

- .editorconfig
- src/app/SIPUserAgents/SIPRegistrationUserAgent.cs
some PBX/Trunks need UserDisplayName in SIP-REGISTER
> SIPRRegister: user display name

- src/core/SIP/SIPConstants.cs
- src/core/SIP/SIPURI.cs
The Canonical address logic is incorrect.
> Revert "SIPURI: MAddr"

- src/core/SIP/SIPURI.cs
- test/core/SIP/SIPURIUnitTest.cs
- test/core/SIPTransactions/SIPTransactionEngineUnitTest.cs
> Recognise invalid IPv6 URIs

- src/app/SIPDNS/SIPDNSManager.cs
- src/net/DNS/Resolver.cs
- test/app/SIPDNSManagerUnitTest.cs
Some minor bug fixes in DNS resolution logic. Added new conditional to dictate whether NAPTR lookups are done, disabled by default.
> Bug fixes and new NAPTR conitional for DNS.

- .github/workflows/sipsorcery-core31-mac.yml
- .github/workflows/sipsorcery-core31-ubuntu.yml
- .github/workflows/sipsorcery-core31-win.yml
- src/sys/Net/NetServices.cs
> Bug fix and new GitHub action jobs for windows & macos

- src/app/SIPUserAgents/SIPRegistrationUserAgent.cs
- test/Initialise.cs
- test/app/SIPUserAgents/SIPRegistrationUserAgentUnitTest.cs
> Added support for custom headers during registration

- src/app/SIPUserAgents/SIPClientUserAgent.cs
- src/app/SIPUserAgents/SIPRegistrationUserAgent.cs
- test/app/SIPUserAgents/SIPClientUserAgentUnitTest.cs
- test/app/SIPUserAgents/SIPRegistrationUserAgentUnitTest.cs
> Added support for adjusting invite and register requests

- src/net/STUN/STUNClient.cs
I had a need for the public IP address in addition to the port number.
Let me know if anything should be changed!
> Added method to get public address and port

- src/app/SIPUserAgents/SIPRegistrationUserAgent.cs
I caught a bug right after you merged the pull request where I assigned a variable to the wrong value
> Assigned variable to wrong value

- examples/SIPExamples/GetStarted/Program.cs
- src/app/SIPUserAgents/SIPUserAgent.cs
> Set From header correctly for SIPUserAgent if authentication is requested

- src/app/SIPUserAgents/SIPUserAgent.cs
> Added early media handling to SIPUserAgent

- src/net/ICE/RtpIceChannel.cs
fix matchingChecklistEntry when same foundation with multiple remoteCandidates
> fix matchingChecklistEntry foundation with multiple remoteCandidates

- examples/webrtccmdline/Program.cs
- examples/webrtccmdline/Properties/launchSettings.json
- examples/webrtccmdline/datachannel.html
- examples/webrtccmdline/webrtc.html
- src/net/ICE/IceChecklistEntry.cs
- src/net/ICE/IceServer.cs
- src/net/ICE/RtpIceChannel.cs
- src/net/STUN/STUNDns.cs
- src/net/STUN/STUNHeader.cs
Gets rid of unwarranted warning messages. Extends the connectivity checks from being capped at 5 to a duration of 15s. Some other small fixes.
> Minor fixes to ICE negotiation

- src/app/Media/MusicMediaSession.cs
- src/app/Media/Sources/EmptyAudioSource.cs
- src/net/RTP/RTPSession.cs
Sorry for the barrage.  Hopefully you find this useful
> MusicMediaSession

- examples/WebRTCExamples/WebRTCExamples.sln
- examples/WebRTCExamples/WebRTCReceiver/Program.cs
- examples/WebRTCExamples/WebRTCReceiver/WebRTCReceiver.csproj
- examples/WebRTCExamples/WebRTCReceiver/captureopts_manlesdp.html
- src/net/WebRTC/RTCPeerConnection.cs
> Fixes bug that was not sending RTCP reports for WebRTC connections

- src/net/DtlsSrtp/DtlsSrtpTransport.cs
- src/net/DtlsSrtp/DtlsUtils.cs
- src/net/DtlsSrtp/Transform/SrtcpTransformer.cs
- src/net/DtlsSrtp/Transform/SrtpTransformer.cs
- src/net/RTP/RTPChannel.cs
* Fixed multithread concurrent error in SrtpTransformer and SrtcpTransformer.
* Fixed RTPChannel Exception while receiving from IPV4 Target on a IPV6 socket in Mono. (issue #336).
* Added support to DTLS-SRTP correct retransmission time based in https://tools.ietf.org/id/draft-ietf-tls-dtls13-31.html#rfc.section.5.
> *Multithread Fixes, Mono RTPChannel Fixes and DTLS-SRTP correct retransmition implementation

- src/net/RTP/RTPSession.cs
- src/net/SCTP/small/SimpleSCTPTimer.cs
Here are a few data channel fixes. Added a null check and a dispose of the timer fix that I mentioned in a bug
> Upstream master2

- src/net/SCTP/Association.cs
- src/net/SCTP/small/UDPForwardingStream.cs
- src/net/STUN/STUNListener.cs
Configured threads to background mode, so app should exit successfully w/o waiting for these worker threads.
> Configured threads to background mode, so app should exit successfully w/o waiting for these worker threads.

- src/app/SIPUserAgents/SIPUserAgent.cs
as mentioned in #414 here are the proposed changes to support telekom.de sip trunk. Only basic calling tested so far.
> 414 telekom de interop issues

- examples/SIPExamples/UserAgentClient/Program.cs
- src/core/SIPTransactions/UACInviteTransaction.cs
@tstaehli this should fix #414.
If it's feasible can you try put this PR to see it solves the signaling with telekom.de.
> Fixes the construction of PRACK requests

- examples/sipcmdline/Program.cs
- src/app/SIPUserAgents/SIPUserAgent.cs
> Adds an optional ring timeout parameter to the SIP user agent calling methods

- src/sys/Crypto/Crypto.cs
> Fixing threading issues with Random

- examples/SIPExamples/UserAgentRegister/Program.cs
Thought it would be nice to improve the docs
> Add delay between registrationUA stop and transport Shutdown in the examples section

- src/core/SIP/SIPTransport.cs
> Make SIPTransport SIP channel dictionary concurrent.

- src/net/RTP/RTPHeader.cs
- src/net/RTP/RTPPacket.cs
Reverts sipsorcery-org/sipsorcery#608
> Revert "Padding bytes should be ignored when parsing RTPPacket"

- src/app/SIPUserAgents/SIPUserAgent.cs
Related to  #631 OnCallHungup does not rise on remote hang up
> Added OnCallHungup on new place

- src/app/Media/IMediaSession.cs
- src/app/SIPUserAgents/SIPUserAgent.cs
- test/unit/Initialise.cs
> Adds an RTP timeout handler to the SIPUserAugent class

- src/net/STUN/STUNClient.cs
> Use STUN XOR attribute for setting public IP address

- src/net/ICE/IceChecklistEntry.cs
- src/net/ICE/IceServer.cs
- src/net/ICE/RtpIceChannel.cs
This should fix WebRTC problem that TURN server drop connection after some period. In case of TURN relay you need to refresh allocation and periodically call CreatePermission to extend lifetime of existing permission.
- Created timer 
- which check if lifetime of Allocation will soon expire. If yes then send Refresh request
- which send CreatePermission minute before permission expiration
- Added logic for handling 438 stale-nonce error. And use nonce from that response in other requests
- Handling Refresh response. Using Lifetime attribute from response to check when the allocation is going to expire
I found out that there is a lot of duplicate code. But I wanted to create solution with minimum changes. That would need some refactoring. And maybe some design changes
Fixes …
> Added TURN refresh allocation and permission

- src/net/STUN/STUNDns.cs
In case of CNAME hostnames, the DNS server returns the list of records where CNAME records are first and A/AAAA records are last.
Since both `ARecord` and `AaaaRecord` classes inherit from the common `AddressRecord` class, I have simplified the code a little bit.
> Support CNAME DNS records

- src/app/SIPUserAgents/SIPUserAgent.cs
Addresses the problem as recorded in #752 
Exceptions arising from calling MediaSession.Start are now handled as follows:
-     An error is Logged and a fail event is raised as appropriate.
-     The call is terminated or rejected as appropriate.
> Unable to handle unexpected exceptions when interacting with the MediaSession (752)

- src/net/RTCP/RTCPSession.cs
- src/net/RTCP/ReceptionReport.cs
Sorry, this is missing change from https://github.com/sipsorcery-org/sipsorcery/commit/17f9514b2ebc4305c532688eec2fe7d2efc7b0dc. I have tested it and it works now.
> Fix Issue in Sender Report RTCP Packet (2nd round)

- src/net/SDP/SDP.cs
- src/net/WebRTC/RTCPeerConnection.cs
- test/integration/net/WebRTC/RTCPeerConnectionUnitTest.cs
MlineIndex was not correctly managed and more specifically when an "application" media was used with other media (audio and/or video).
Add unit test to ensure this will not happen anymore.
Fix https://github.com/sipsorcery-org/sipsorcery/issues/757
> MlineIndex was not correctly managed

- src/net/STUN/STUNDns.cs
minor change needed for proper work of DnsUseTcpFallback  #750
> Recreating _lookupClient if DnsUseTcpFallback value was changed

- src/SIPSorcery.csproj
Add net6.0 as target fwk. It was removed by error.
> Add net6.0 as target fwk.

- src/net/DtlsSrtp/DtlsSrtpTransport.cs
- src/net/RTP/RTPSession.cs
SIP Context: Problem to get MediaStream using SSRC (no SSRC specified in SDP) (fix #770)
> SIP Context: Problem to get MediaStream using SSRC (no SSRC specified in SDP) (fix #770)

- src/core/SIP/Channels/SIPTLSChannel.cs
Adding custom cert validation in a non-breaking way
> Adding custom remote certificate callback for the Sip tls channel

- src/SIPSorcery.csproj
> update dnsclient nuget package

- src/net/SCTP/SctpDataReceiver.cs
Replaces https://github.com/sipsorcery-org/sipsorcery/pull/782. See there for discussion.
> SCTP gracefully handle full reordering queue

- src/core/SIPTransactions/SIPTransactionEngine.cs
The Thread.Sleep() in SIPTransactionEngine.cs causes significant slow down particularly in large integration tests. This change has taken 80% off the time that some of our integration tests take to run.
The premise is that as soon as a new transaction is queued the transaction engine wakes up. Previously it would continue to sleep for 200ms if the pending transaction list was empty, or 50ms if it had just processed the pending transaction list.
> Process new transactions immediately

- src/app/SIPUserAgents/SIPRegistrationUserAgent.cs
I think its good to get Response info
> Inject `SIPResponse` into `SIPRegistrationUserAgent Events`

- src/core/SIP/SIPResponse.cs
Added an IsSuccessStatusCode property similar to the property in HttpMessageResponse.
> Added IsSuccessStatusCode property to SIPResponse

- src/app/Media/Sources/AudioExtrasSource.cs
I had some crashes in SendStreamSample which I couldn't even handle with try-catches at my end, because they were crashing the whole application, and this is the only way I found I could avoid them.
> Improved robustness in SendStreamSample

- src/net/RTP/RTPSession.cs
Signed-off-by: Pranav Pandit <pranavp@microsoft.com>
Fixes #843
> Fix handling of XR RTCP packets in RTPSession

- src/app/SIPUserAgents/SIPUserAgent.cs
Hello! This PR is connected with issue https://github.com/sipsorcery-org/sipsorcery/issues/818
There can be two race-conditions both occurs when call is being answered and CANCELLed at the same time. For example:
Application receives SIP INVITE, answer with  
INVITE 100 Trying  
INVITE 180 Ringing  
but does not send INVITE 200 Ok right away (this is our use-case)
while client becomes ready to fully answer call, telephony server sends CANCEL command. In rare occasions it can lead to observed or unobserved exceptions.
If call answered before CANCEL (but still at the same time), there will be this message at Error level:
```
Exception SIPMessageReceived. Object reference not set to an instance of an object.
BadRequest Received udp:localip:54533<-udp:asteriskip:5060: message - Exception …
```
> Synchronize call answer and end methods

- src/app/SIPUserAgents/SIPUserAgent.cs
- test/integration/app/SIPUserAgentUnitTest.cs
In the current implementation content passed by the client in SIPCallDescriptor was always overridden by the SDP offer while initiating the call. However, there are some scenarios when the client wants to pass multipart content. 
After this change, if the client passes non-null content it wouldn't be changed, if the content is null it would be replaced by SDP offer. 
Added unit tests to cover those scenarios.
> Allow clients to pass custom content while initiating call by setting SIPCallDescritor content field

- src/core/DNS/SIPDns.cs
- src/core/SIP/SIPTransport.cs
Added missing dns cache lookup answers filter and uri resolve from cache result checks
> Fix issues with uri resolve

- src/net/ICE/RtpIceChannel.cs
This fixes an exception that is randomly crashing the application due to a race condition.
> Fix for a random InvalidOperationException #902

- src/core/SIP/SIPTransport.cs
- src/net/ICE/RtpIceChannel.cs
- src/net/RTCP/RTCPCompoundPacket.cs
- src/net/RTCP/RTCPSdesReport.cs
- src/net/RTCP/RTCPSession.cs
- src/net/RTP/RTPHeader.cs
- src/net/RTP/RTPPacket.cs
- src/net/RTSP/RTSPHeader.cs
- src/net/RTSP/RTSPRequest.cs
- src/sys/Net/NetServices.cs
- test/unit/net/RTP/RTPHeaderUnitTest.cs
This provides more flexibility.
> Fix some bugs and enhance robustness

- src/net/WebRTC/RTCDataChannel.cs
Data Channel Open Message will be correct but not sure that all ChannelType are really supported
> Fix Data Channel Open Message: Protocol was missing and ChannelType was hardcoded

- src/app/Media/Sources/AudioExtrasSource.cs
#942 AudioExtrasSource ObjectDisposedException: Cannot access a closed stream
> #942 AudioExtrasSource ObjectDisposedException

- src/net/ICE/RtpIceChannel.cs
Partially fixes https://github.com/sipsorcery-org/sipsorcery/issues/743
Major operating systems support mDNS resolution out of the box (Windows, desktop Linux, and MacOS).
This change is backwards compatible in the sense that the system resolver would only kick in unless user explicitly set `MdnsResolve`.
It is not backwards compatible in the sense that some ICE candidates that previously were not resolved now might start getting resolved.
P.S. Did not test on mobile.
> Use system resolver to resolve mDNS names by default

- src/app/Media/Sources/AudioExtrasSource.cs
> Fixed race condition while using timers to send audio samples.

- src/core/SIP/Channels/SIPTLSChannel.cs
- test/integration/core/SIPTransportIntegrationTest.cs
When a TLS channel is active, it is possible to block all further TLS connections by opening a TCP connection that never completes the TLS handshake.
This is because the TLS channel would handle incoming connections sequentially and wait indefinitely on the `sslStream.AuthenticateAsServer(m_serverCertificate)` until the client also calls the corresponding `AuthenticateAsClient()` which will never happen.
My PR fixes this by handling all connection atttempts concurrently, and also adds a timeout to close the ssl stream to prevent the incomplete connection from clogging resources
To reproduce the issue, open a TCP client and target the TLS channel's ip:port. 
While the TCP client is active, try to establish a TLS connection (such as sending a REGISTER request over TLS)
The TLS connection …
> TLS Channel would be blocked by pending TCP connection

- src/SIPSorcery.csproj
- src/net/DtlsSrtp/DtlsSrtpClient.cs
- src/net/DtlsSrtp/DtlsSrtpServer.cs
- src/net/DtlsSrtp/DtlsSrtpTransport.cs
- src/net/DtlsSrtp/DtlsUtils.cs
- src/net/DtlsSrtp/SrtpParameters.cs
- src/net/WebRTC/IRTCPeerConnection.cs
- src/net/WebRTC/RTCPeerConnection.cs
- src/net/WebRTC/RTCSctpTransport.cs
- test/integration/net/DtlsSrtp/DtlsSrtpTransportUnitTest.cs
- test/integration/net/DtlsSrtp/DtlsUtilsUnitTest.cs
Reverts sipsorcery-org/sipsorcery#1022
> Revert "Upgrade bouncycastle to v2"

- src/net/RTP/Packetisation/RtpVP8Header.cs
Fixes #1040
I have tested and solved the problem in my cases
Before I was unable to decode VP8 packets coming from my Android phone.
After Android Phone video image is Present and Clean
In addition:
Before: vp8Header.IsKeyFrame was not implemented.
After: vp8Header.IsKeyFrame is true for VP8Keyframes
> Fixes #1040 VP8 Payload Descriptor is miscalculated for some packets

- src/net/RTP/RTPSession.cs
- src/net/WebRTC/RTCPeerConnection.cs
Store correct capabilities in LocalTrack
Fix #981
> Store correct capabilities in LocalTrack

- examples/WebRTCScenarios/DataChannelBandwidth/BandwidthTestProgram.cs
- examples/WebRTCScenarios/DataChannelBandwidth/DataChannelBandwidth.csproj
- examples/WebRTCScenarios/DataChannelBandwidth/DataChannelBandwidth.sln
- examples/WebRTCScenarios/DataChannelBandwidth/DataChannelStream.cs
The state is sad: data channels rapidly crumble under pressure and stop transmitting data (not to mention excessive memory allocation, but that can be addressed after the stability issue is solved).
> Added data channel bandwidth test program

- src/app/SIPUserAgents/ISIPClientUserAgent.cs
- src/app/SIPUserAgents/SIPB2BUserAgent.cs
- src/app/SIPUserAgents/SIPClientUserAgent.cs
- src/core/SIPTransactions/UACInviteTransaction.cs
> UAC send manuel Acknowledge(OK) with SDP

- src/net/ICE/RtpIceChannel.cs
A fix for an exception that cannot be caught outside the library. Probably a race condition
> Fix InvalidOperationException (#1173)

- src/app/Media/Sources/AudioExtrasSource.cs
- Adds support for 24kHz and 44.1kHz sampling rates
- https://github.com/sipsorcery-org/SIPSorceryMedia.Abstractions/pull/8
> cast sample rate to int

- src/net/WebRTC/RTCPeerConnection.cs
Added the setting of protocol in OnSctpAssociationNewDataChannel.
> Set protocol when creating a new data channel

- src/app/SIPUserAgents/SIPRegistrationUserAgent.cs
> Fix bug not disposing of SIP register timer.

- examples/WebRTCExamples/WebRTCReceiver/Program.cs
- examples/WebRTCExamples/WebRTCReceiver/WebRTCReceiver.csproj
> Updated webrtcreceiver dotnet version and nuget packages and added missing ffmpeg init command.

- examples/SIPExamples/UserAgentClient/Program.cs
- src/SIPSorcery.csproj
- src/app/Media/VoIPMediaSession.cs
- src/net/RTP/MediaStream.cs
- src/net/RTP/RTPSession.cs
- test/integration/SIPSorcery.IntegrationTests.csproj
- test/unit/SIPSorcery.UnitTests.csproj
Additionally updated target from 461 to 462 to allow removal of vuln xunit packages.
> Updated vuln nuget pkgs

- src/net/SDP/SDP.cs
- test/unit/net/SDP/SDPUnitTests.cs
Tightened up the SDP owner parsing.
> Added a unit test to check the SDP media format order

- src/net/ICE/RtpIceChannel.cs
> Updated getting authenticated STUN request to use FIPS compliant library.

- examples/WebRTCExamples/WebRTCChatGPT/Program.cs
- examples/WebRTCExamples/WebRTCChatGPT/WebRTCChatGPT.csproj
- examples/WebRTCExamples/WebRTCChatGPT/chatgpt.html
- examples/WebRTCExamples/WebRTCExamples.sln
- examples/webrtccmdline/Program.cs
The browser based js version currently works. The C# version can establish a WebRTC peers connection but is not getting a data channel response.
> Added webrtc example for connectiing to openapi's realtime webrtc server

- examples/WebRTCExamples/WebRTCChatGPT/Program.cs
- src/SIPSorcery.csproj
- src/app/Media/Codecs/AudioEncoder.cs
OPUS codec not currently working properly. Will need more work in a separate PR.
> ChatGPT sample connects as long as OPUS offered

- examples/SIPExamples/ReceiveDtmf/Program.cs
- examples/SIPExamples/ReceiveDtmf/ReceiveDtmf.csproj
- examples/SIPExamples/SIPExamples.sln
- examples/SIPExamples/SendDtmf/Program.cs
- src/app/Media/VoIPMediaSession.cs
- src/net/RTP/RTPSession.cs
> Fixed RTP event negotiation to set common ID if remote party is not using 101

- src/core/SIP/SIPConstants.cs
- test/unit/core/SIP/SIPRequestUnitTest.cs
- Added support for SERVICE method
- Added UT for the same
> Adding SERVICE method

- examples/OpenAIExamples/WebRTCOpenAI/Program.cs
- src/app/Media/Codecs/AudioEncoder.cs
- src/sys/TypeExtensions.cs
Hi,
I recently discovered this project while tinkering on a side project. I'm impressed by the amount of work that has been done. Congrats to the project leader and the contributors.
I submit this pull request to fix a few typos I found while reading the code.
I might submit other minor PRs in the near future.
Let me know if there are some guidelines to follow for contributing.
Cheers,
Remi
> Fix a few typos found while reading the code.

- src/core/TWCCBitrateController.cs
- src/net/RTCP/TWCCBitrateController.cs
Bitrate and framerate controller - can be used by clients to adjust video streams for network conditions.
> Add a Bitrate Controller

- src/net/RTP/VideoStream.cs
Should just be a minor change,
Because I'm pretty sure conditional check of enum is slightly faster than strings...
> Refactor VideoStream sending format conditional

- src/net/RTP/RTPSession.cs
> Reverts a local video stream null check change in rtp session from #1331

- src/net/WebRTC/WebRTCWebSocketPeerAspNet.cs
After signaling and connection succeed, the signaling channel is now quiet, too quiet, and the websocket peer will close the stream if signaling is closed.
```
The remote party closed the WebSocket connection without completing the close handshake.
```
```
WebSocket closed, code: 1006, reason:
```
This PR sends a `ping` message periodically (30s) to prevent this disconnection.
And adds minor QOL to be able to close websockets upon app shutdown (by cancel token).
> Add keepalive param and host shutdown mechanism for WebSocketPeer signaling

- src/core/SIP/Channels/SIPWebSocketChannel.cs
Fixes the issue outlined in #1436
Added a way to change the TLS version that is used by the `SIPWebSocketChannel`. Was set to TLS 1.0 before.
The default is kept on the old obsolete version.
Also wired up the `SendSecureAsync` method with the `SendAsync` method so the data channel can be used with the `SIPTransport` class.
> wss implementation for SIPWebSocketChannel 

- src/sys/Net/NetServices.cs
Return cached ip only when it is valid
> Local addresses cache validity check
